name: TweakFurnace
main: net.tweakcraft.TweakFurnace.TweakFurnace
authors:
    - GuntherDW
    - Edoxile
website: https://github.com/Edoxile/TweakFurnace
version: 0.1
commands:
    tfmute:
        description: Toggle mute for this plugin
        usage: /<command>
