name: TweakFurnace
main: net.tweakcraft.TweakFurnace.TweakFurnace
authors:
    - GuntherDW
    - Edoxile
    - GuntherDW
    - GuntherDW
website: https://github.com/Edoxile/TweakFurnace
version: 0.2
commands:
    tfmute:
        description: Toggle mute for this plugin
        usage: /<command>
        aliases: [tfm]
    tfamount:
        description: Toggle amount for furnace input
        usage: /<command>
        aliases: [tfa]
